dist: trusty
language: node_js
node_js:
  - "12"
addons:
  chrome: stable
install:
  - yarn install
script:
  - yarn run build
  - yarn run run-node-spec
  - yarn run run-web-spec
cache:
  yarn: true
  directories:
    - "node_modules"